fix: Pick random video logic infinite loop
BrightcovePS/react-native-brightcove-player pull request #17
Opened 2022-04-07 09:35 UTC by parunagiri

Hi @backer,
Pick random video logic infinite loop issue when video cloud has only one video in that account. Added if condition to perform if videos list more than one video.

Have a nice day

2022-04-07 15:19 UTC, backer requested changes

2022-04-07 15:19 UTC, backer commented on android/src/main/java/jp/manse/up_next/UpNextViewOverlay.java
> +        if(allVideos != null && allVideos.getVideos() != null && allVideos.getVideos().size() > 1) {
formatting is wrong, remember to run formatter after every change before committing

2022-04-08 04:52 UTC, parunagiri commented on android/src/main/java/jp/manse/up_next/UpNextViewOverlay.java
> +        if(allVideos != null && allVideos.getVideos() != null && allVideos.getVideos().size() > 1) {
I am almost every time. Let me make this automatic formatting on android studio

2022-04-08 19:56 UTC, backer approved these changes
👍

2022-04-11 05:52 UTC, merged