Refactor/lib upgrade
BrightcovePS/react-native-brightcove-player pull request #2
Opened 2022-02-09 10:27 UTC by parunagiri

Update the Android library version and build Gradle code as well. Fixed version upgrade dependencies

2022-02-09 19:34 UTC, backer requested changes

2022-02-09 19:34 UTC, backer commented on android/build.gradle
> +        minSdkVersion 16
this should be 21 now

2022-02-09 19:34 UTC, backer commented on android/build.gradle
> +    compileSdkVersion 29
this should match targetSdkVersion

2022-02-09 19:34 UTC, backer commented on android/build.gradle
> +    if (project == rootProject) {
any particular reason for this?

2022-02-09 19:34 UTC, backer commented on android/build.gradle
> +    implementation "com.facebook.react:react-native:+"  // From node_modules
I know that this was already set to + but we try to avoid using + versions, so can we change this to use the latest version?

2022-02-09 19:34 UTC, backer commented on android/src/main/java/jp/manse/BrightcovePlayerPosterView.java
> +        this.offlineCatalog = new OfflineCatalog.Builder(context, DefaultEventEmitter.sharedEventEmitter, accountId)
why the extra init call here?

2022-02-09 19:34 UTC, backer commented on android/src/main/java/jp/manse/BrightcovePlayerPosterView.java
> +        if(accountId == null || policyKey == null) return;
formatting, should have space in between `if (` and we like to use brackets even for one line if statements unless using kotlin assignments with if/else

2022-02-09 19:34 UTC, backer commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +        if(accountId == null || policyKey == null) return;
same here, or combine this with the next if to avoid nested/extra statements

2022-02-10 04:15 UTC, parunagiri commented on android/build.gradle
> +    if (project == rootProject) {
Maven and google repo needed project-specific Gradle if the root project itself project we are adding the repo. This has been derived react-native package template project.

2022-02-10 05:08 UTC, parunagiri commented on android/build.gradle
> +    implementation "com.facebook.react:react-native:+"  // From node_modules
There is a proper way to replace it with a specific version.  When trying to update with a specific version as like below 
implementation "com.facebook.react:react-native:0.67.1"

I am getting the below error on the build issue. Also, we don't have the official doc or release artifacts page for android react native library 

Could not determine the dependencies of task ':react-native-brightcove-player:compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':react-native-brightcove-player:releaseCompileClasspath'.
   > Could not find com.facebook.react:react-native:0.67.1.
     Required by:
         project :react-native-brightcove-player

2022-02-10 22:27 UTC, backer approved these changes
thanks for updating 👍

2022-02-11 08:25 UTC, merged