Committing player controls and overlays
BrightcovePS/react-native-brightcove-player pull request #8
Opened 2022-03-18 11:53 UTC by PratheeshDBennet

Hi @backer , 

Please find the PR as discussed. Once again thanks a lot and as discussed I'll be careful considering PR before development. 

[feature player controls] - Player custom controls layout and overlay controls
[feature Thumbnail overlay] - To display an overlay for the next video at the end of a video

The folders that were mostly reused from Media Corp are (In case if you feel to skip or do light reviews)
-  CustomPlayerView/Gridview
-  CustomPlayerView/Network

Notes: 

- There are some print logs in the swipe gesture module that will be removed 
- Certain features such as PIP, Airplay are developed as small plugin components and the calling interfaces are commented (Considering we are making as a reusable solution, the plugin components I have included)
- The all-video API policy keys and account id are hardcoded which will be removed. 
- Some hardcoded recommendations objects are in code in gridviewmodel.swift which will be removed. 

Thanks and regards.

2022-03-22 20:17 UTC, backer requested changes
So the changes look good, just left one comment about the videos limit. 

However, it seems like the formatting of all the files was broken with indentation getting removed/reduced and some double spaces in some places. Could you please make sure the formatting is fixed? Thanks!

2022-03-22 20:17 UTC, backer commented on ios/CustomPlayerView/AccountConfig/AccountConfig.swift
> +  static let allVideosLimit: Int = 250
We can make this 1000 with the new Playback API allowance

2022-03-23 07:15 UTC, PratheeshDBennet commented on ios/CustomPlayerView/AccountConfig/AccountConfig.swift
> +  static let allVideosLimit: Int = 250
Thank you very much for your time. 

- Sure will make the limit as 1000. 

- Reg some double spaces in some places - Sure will take care of it. 

- Reg the Indentation getting removed/reduced - I have set the indent tab spacing as specified in the BGS swift coding standards [https://github.com/BGS-Libraries/styleguide-swift#spacing](url) (generally followed spacing), so that's why maybe it looks to be a bit reduced or removed.

2022-03-23 14:52 UTC, backer approved these changes
👍

2022-03-23 16:05 UTC, merged