Feature/custom controls
BrightcovePS/react-native-brightcove-player pull request #9
Opened 2022-03-21 06:15 UTC by parunagiri

Custom controls has been design for redbull

2022-03-22 20:29 UTC, backer requested changes

2022-03-22 20:29 UTC, backer commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +        BrightcovePlayerView.this.playerVideoView.setOnPreparedListener(mp -> {
Was there an issue with this? What is the purpose of this change? Calling start should be all that's necessary here

2022-03-22 20:29 UTC, backer commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +import android.media.MediaPlayer;
MediaPlayer should not be used, is this an accidental import?

2022-03-22 20:29 UTC, backer commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +            if(seekMax > seekPos) {
nit: formatting, should have space after if

2022-03-22 20:29 UTC, backer commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +        }else if (v.getId() == R.id.rewind_btn) {
formatting, space after bracket

2022-03-22 20:29 UTC, backer commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +    private final OnClickListener controlsClickListener = v -> {
This should have a more specific name since this does not cover all player controls clicks

2022-03-22 20:29 UTC, backer commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +            eventEmitter.emit(EventType.REWIND);
Are these for the skip forward/backward controls or basic FF/RW? If the former, this should have skip back logic here right?

2022-03-22 20:29 UTC, backer commented on android/src/main/res/layout/player_controls.xml
> +    android:padding="8dp"
use dimen res

2022-03-23 04:39 UTC, parunagiri commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +        BrightcovePlayerView.this.playerVideoView.setOnPreparedListener(mp -> {
Initial video auto-plays do not work. It's because the player was not yet ready to play the content. So I moved the start method inside on prepare listener. I have verified all the way. Thanks for asking about clarification

2022-03-23 04:43 UTC, parunagiri commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +import android.media.MediaPlayer;
Yes, it's accidental. I removed it.

2022-03-23 04:44 UTC, parunagiri commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +            if(seekMax > seekPos) {
Done

2022-03-23 04:45 UTC, parunagiri commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +        }else if (v.getId() == R.id.rewind_btn) {
Done

2022-03-23 04:49 UTC, parunagiri commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +    private final OnClickListener controlsClickListener = v -> {
Done

2022-03-23 04:53 UTC, parunagiri commented on android/src/main/java/jp/manse/BrightcovePlayerView.java
> +            eventEmitter.emit(EventType.REWIND);
Skip backward works out of the box from SDK so do need to rewind logic here.

2022-03-23 13:58 UTC, backer approved these changes
thanks for updating/answering! 👍

2022-03-23 14:01 UTC, merged